name: place
description: Event ticketing application
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  intl: ^0.19.0

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-Regular.ttf
        - asset: assets/fonts/urbanist/Urbanist-SemiBold.ttf
        - asset: assets/fonts/urbanist/Urbanist-Medium.ttf
        - asset: assets/fonts/urbanist/Urbanist-Bold.ttf
          weight: 700